#!/bin/bash
############################################################
## 'man qsub' for additional information.
############################################################

#SBATCH -J CFE4D
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --mem-per-cpu=4000 
#SBATCH -t 24:00:00

module load intel
module load openmpi

cat /home/bantilan/numrel/CFE4D/src/CFE4D.fparam rtparam > localCFE4D.param
/bin/cp /home/bantilan/numrel/CFE4D/src/CFE4D localCFE4D
srun ./localCFE4D localCFE4D.param | tee out
